In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../data/sales_data.csv")

In [3]:
df.head()

,Transaction_ID,Date,Branch,Product,Category,Quantity,Unit_Price,Payment_Method,Customer_Type
0,TXN0191,2026-01-01,Entebbe,Shampoo,Personal Care,3,22000,Card,Regular
1,TXN0113,2026-01-02,Entebbe,Electric Kettle,Home & Kitchen,3,95000,Mobile Money,Regular
2,TXN0499,2026-01-02,Jinja,Smartphone,Electronics,5,850000,Mobile Money,New
3,TXN0140,2026-01-03,Jinja,Frying Pan,Home & Kitchen,2,65000,Cash,New
4,TXN0150,2026-01-04,Jinja,Cooking Oil 3L,Groceries,5,28000,Cash,Regular

In [4]:
df.tail()

,Transaction_ID,Date,Branch,Product,Category,Quantity,Unit_Price,Payment_Method,Customer_Type
495,TXN0065,2026-07-29,Jinja,Jeans,Clothing,3,85000,Card,New
496,TXN0127,2026-07-29,Kampala,Body Lotion,Personal Care,3,25000,Cash,New
497,TXN0319,2026-07-29,Kampala,Laptop Bag,Electronics,5,85000,Cash,Regular
498,TXN0080,2026-07-30,Kampala,Cooking Oil 3L,Groceries,2,28000,Cash,New
499,TXN0411,2026-07-30,Jinja,Laptop Bag,Electronics,2,85000,Cash,New

In [5]:
df.shape

(500, 9)

In [6]:
df.columns

Index(['Transaction_ID', 'Date', 'Branch', 'Product', 'Category', 'Quantity',
       'Unit_Price', 'Payment_Method', 'Customer_Type'],
      dtype='str')

In [7]:
df.dtypes

Transaction_ID      str
Date                str
Branch              str
Product             str
Category            str
Quantity          int64
Unit_Price        int64
Payment_Method      str
Customer_Type       str
dtype: object

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Transaction_ID  500 non-null    str
 1   Date            500 non-null    str
 2   Branch          500 non-null    str
 3   Product         500 non-null    str
 4   Category        500 non-null    str
 5   Quantity        500 non-null    int64
 6   Unit_Price      500 non-null    int64
 7   Payment_Method  500 non-null    str
 8   Customer_Type   500 non-null    str
dtypes: int64(2), str(7)
memory usage: 62.4 KB

In [9]:
df.isnull().sum()

Transaction_ID    0
Date              0
Branch            0
Product           0
Category          0
Quantity          0
Unit_Price        0
Payment_Method    0
Customer_Type     0
dtype: int64

In [10]:
df.duplicated().sum()

np.int64(0)

In [11]:
df.describe()

         Quantity     Unit_Price
count  500.000000     500.000000
mean     3.026000  109638.000000
std      1.381717  183726.693629
min      1.000000   12000.000000
25%      2.000000   25000.000000
50%      3.000000   65000.000000
75%      4.000000  101250.000000
max      5.000000  850000.000000

Inspect categorical columns

In [12]:
df["Branch"].unique()

<ArrowStringArray>
['Entebbe', 'Jinja', 'Kampala']
Length: 3, dtype: str

In [14]:
df["Category"].unique()

<ArrowStringArray>
['Personal Care', 'Home & Kitchen', 'Electronics', 'Groceries', 'Clothing']
Length: 5, dtype: str

In [15]:
df["Payment_Method"].unique()

<ArrowStringArray>
['Card', 'Mobile Money', 'Cash']
Length: 3, dtype: str

In [16]:
df["Branch"].value_counts()

Branch
Jinja      175
Kampala    163
Entebbe    162
Name: count, dtype: int64

In [17]:
df.dtypes

Transaction_ID      str
Date                str
Branch              str
Product             str
Category            str
Quantity          int64
Unit_Price        int64
Payment_Method      str
Customer_Type       str
dtype: object

In [18]:
df["Date"] = pd.to_datetime(df["Date"])

In [20]:
df.dtypes

Transaction_ID               str
Date              datetime64[us]
Branch                       str
Product                      str
Category                     str
Quantity                   int64
Unit_Price                 int64
Payment_Method               str
Customer_Type                str
dtype: object

Calculate revenue for every transaction

In [21]:
df["Total_Sales"] = df["Quantity"] * df["Unit_Price"]

In [22]:
df.head()

,Transaction_ID,Date,Branch,Product,Category,Quantity,Unit_Price,Payment_Method,Customer_Type,Total_Sales
0,TXN0191,2026-01-01,Entebbe,Shampoo,Personal Care,3,22000,Card,Regular,66000
1,TXN0113,2026-01-02,Entebbe,Electric Kettle,Home & Kitchen,3,95000,Mobile Money,Regular,285000
2,TXN0499,2026-01-02,Jinja,Smartphone,Electronics,5,850000,Mobile Money,New,4250000
3,TXN0140,2026-01-03,Jinja,Frying Pan,Home & Kitchen,2,65000,Cash,New,130000
4,TXN0150,2026-01-04,Jinja,Cooking Oil 3L,Groceries,5,28000,Cash,Regular,140000

Verify the calculation

In [23]:
df[["Quantity", "Unit_Price", "Total_Sales"]].head(10)

   Quantity  Unit_Price  Total_Sales
0         3       22000        66000
1         3       95000       285000
2         5      850000      4250000
3         2       65000       130000
4         5       28000       140000
5         3       32000        96000
6         1      150000       150000
7         3      150000       450000
8         5       95000       475000
9         2       85000       170000

Extract the year

In [24]:
df["Date"].dt

Create a Year column:

In [25]:
df["Year"] = df["Date"].dt.year

In [26]:
df.head()

,Transaction_ID,Date,Branch,Product,Category,Quantity,Unit_Price,Payment_Method,Customer_Type,Total_Sales,Year
0,TXN0191,2026-01-01,Entebbe,Shampoo,Personal Care,3,22000,Card,Regular,66000,2026
1,TXN0113,2026-01-02,Entebbe,Electric Kettle,Home & Kitchen,3,95000,Mobile Money,Regular,285000,2026
2,TXN0499,2026-01-02,Jinja,Smartphone,Electronics,5,850000,Mobile Money,New,4250000,2026
3,TXN0140,2026-01-03,Jinja,Frying Pan,Home & Kitchen,2,65000,Cash,New,130000,2026
4,TXN0150,2026-01-04,Jinja,Cooking Oil 3L,Groceries,5,28000,Cash,Regular,140000,2026

Create the month number

In [27]:
df["Month"] = df["Date"].dt.month

In [30]:
df[["Date", "Month"]].head()

        Date  Month
0 2026-01-01      1
1 2026-01-02      1
2 2026-01-02      1
3 2026-01-03      1
4 2026-01-04      1

Create a Month Name column:

In [31]:
df["Month_Name"] = df["Date"].dt.month_name()

In [32]:
df[["Date", "Month", "Month_Name"]].head()

        Date  Month Month_Name
0 2026-01-01      1    January
1 2026-01-02      1    January
2 2026-01-02      1    January
3 2026-01-03      1    January
4 2026-01-04      1    January

Create day information

extract the day of the month

In [33]:
df["Day"] = df["Date"].dt.day

And the weekday name:

In [34]:
df["Day_Name"] = df["Date"].dt.day_name()

In [35]:
df[["Date", "Day", "Day_Name"]].head()

        Date  Day  Day_Name
0 2026-01-01    1  Thursday
1 2026-01-02    2    Friday
2 2026-01-02    2    Friday
3 2026-01-03    3  Saturday
4 2026-01-04    4    Sunday

Create a month-period column  
it will make monthly charts easier later.

In [36]:
df["Year_Month"] = df["Date"].dt.to_period("M").astype(str)

In [37]:
df.head()

,Transaction_ID,Date,Branch,Product,Category,Quantity,Unit_Price,Payment_Method,Customer_Type,Total_Sales,Year,Month,Month_Name,Day,Day_Name,Year_Month
0,TXN0191,2026-01-01,Entebbe,Shampoo,Personal Care,3,22000,Card,Regular,66000,2026,1,January,1,Thursday,2026-01
1,TXN0113,2026-01-02,Entebbe,Electric Kettle,Home & Kitchen,3,95000,Mobile Money,Regular,285000,2026,1,January,2,Friday,2026-01
2,TXN0499,2026-01-02,Jinja,Smartphone,Electronics,5,850000,Mobile Money,New,4250000,2026,1,January,2,Friday,2026-01
3,TXN0140,2026-01-03,Jinja,Frying Pan,Home & Kitchen,2,65000,Cash,New,130000,2026,1,January,3,Saturday,2026-01
4,TXN0150,2026-01-04,Jinja,Cooking Oil 3L,Groceries,5,28000,Cash,Regular,140000,2026,1,January,4,Sunday,2026-01

In [38]:
df.isnull().sum()

Transaction_ID    0
Date              0
Branch            0
Product           0
Category          0
Quantity          0
Unit_Price        0
Payment_Method    0
Customer_Type     0
Total_Sales       0
Year              0
Month             0
Month_Name        0
Day               0
Day_Name          0
Year_Month        0
dtype: int64

In [39]:
df.duplicated().sum()

np.int64(0)

Check invalid quantities and prices

In [40]:
df[df["Quantity"] <= 0]

Empty DataFrame
Columns: [Transaction_ID, Date, Branch, Product, Category, Quantity, Unit_Price, Payment_Method, Customer_Type, Total_Sales, Year, Month, Month_Name, Day, Day_Name, Year_Month]
Index: []

In [41]:
df[df["Unit_Price"] <= 0]

Empty DataFrame
Columns: [Transaction_ID, Date, Branch, Product, Category, Quantity, Unit_Price, Payment_Method, Customer_Type, Total_Sales, Year, Month, Month_Name, Day, Day_Name, Year_Month]
Index: []

In [42]:
df[df["Total_Sales"] <= 0]

Empty DataFrame
Columns: [Transaction_ID, Date, Branch, Product, Category, Quantity, Unit_Price, Payment_Method, Customer_Type, Total_Sales, Year, Month, Month_Name, Day, Day_Name, Year_Month]
Index: []

Check our categories

In [43]:
df["Branch"].value_counts()

Branch
Jinja      175
Kampala    163
Entebbe    162
Name: count, dtype: int64

In [44]:
df["Category"].value_counts()

Category
Groceries         112
Home & Kitchen    103
Clothing           99
Personal Care      97
Electronics        89
Name: count, dtype: int64

In [45]:
df["Payment_Method"].value_counts()

Payment_Method
Card            174
Mobile Money    169
Cash            157
Name: count, dtype: int64

In [46]:
df["Customer_Type"].value_counts()

Customer_Type
Regular    262
New        238
Name: count, dtype: int64

In [47]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 16 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Transaction_ID  500 non-null    str
 1   Date            500 non-null    datetime64[us]
 2   Branch          500 non-null    str
 3   Product         500 non-null    str
 4   Category        500 non-null    str
 5   Quantity        500 non-null    int64
 6   Unit_Price      500 non-null    int64
 7   Payment_Method  500 non-null    str
 8   Customer_Type   500 non-null    str
 9   Total_Sales     500 non-null    int64
 10  Year            500 non-null    int32
 11  Month           500 non-null    int32
 12  Month_Name      500 non-null    str
 13  Day             500 non-null    int32
 14  Day_Name        500 non-null    str
 15  Year_Month      500 non-null    str
dtypes: datetime64[us](1), int32(3), int64(3), str(9)
memory usage: 88.4 KB

In [48]:
df.describe()

,Date,Quantity,Unit_Price,Total_Sales,Year,Month,Day
count,500,500.000000,500.000000,5.000000e+02,500.0,500.000000,500.000000
mean,2026-04-18 07:29:16.800000,3.026000,109638.000000,3.342080e+05,2026.0,4.058000,16.296000
min,2026-01-01 00:00:00,1.000000,12000.000000,1.200000e+04,2026.0,1.000000,1.000000
25%,2026-02-25 18:00:00,2.000000,25000.000000,6.500000e+04,2026.0,2.000000,9.000000
50%,2026-04-23 00:00:00,3.000000,65000.000000,1.400000e+05,2026.0,4.000000,17.000000
75%,2026-06-07 18:00:00,4.000000,101250.000000,3.400000e+05,2026.0,6.000000,24.000000
max,2026-07-30 00:00:00,5.000000,850000.000000,4.250000e+06,2026.0,7.000000,31.000000
std,NaN,1.381717,183726.693629,6.418022e+05,0.0,1.967327,8.674727

In [49]:
df.to_csv("../data/cleaned_sales_data.csv", index=False)

How much revenue did Jjuuko Retail Stores generate?

In [50]:
total_revenue = df["Total_Sales"].sum()

total_revenue

np.int64(167104000)

In [51]:
print(f"Total Revenue: UGX {total_revenue:,.0f}")

Total Revenue: UGX 167,104,000

How many transactions occurred?

In [52]:
total_transactions = df["Transaction_ID"].nunique()

print("Total Transactions:", total_transactions)

Total Transactions: 500

Calculate total units sold

In [54]:
total_units = df["Quantity"].sum()

print("Total Units Sold:", total_units)

Total Units Sold: 1513

Calculate average transaction value

In [56]:
average_transaction_value = total_revenue / total_transactions

print(f"Average Transaction Value: UGX {average_transaction_value:,.0f}")

Average Transaction Value: UGX 334,208

Revenue by branch

In [58]:
revenue_by_branch = (
    df.groupby("Branch")["Total_Sales"]
    .sum()
    .sort_values(ascending=False)
)

revenue_by_branch

Branch
Jinja      55816000
Kampala    55728000
Entebbe    55560000
Name: Total_Sales, dtype: int64

Revenue by category

In [59]:
revenue_by_category = (
    df.groupby("Category")["Total_Sales"]
    .sum()
    .sort_values(ascending=False)
)

revenue_by_category

Category
Electronics       90990000
Home & Kitchen    32965000
Clothing          28790000
Groceries          8156000
Personal Care      6203000
Name: Total_Sales, dtype: int64

Revenue by product

In [61]:
revenue_by_product = (
    df.groupby("Product")["Total_Sales"]
    .sum()
    .sort_values(ascending=False)
)

revenue_by_product

Product
Smartphone         72250000
Jacket             15600000
Blender            15120000
Electric Kettle    11020000
Headphones         10920000
Jeans               9095000
Laptop Bag          7820000
Frying Pan          6825000
T-Shirt             4095000
Cooking Oil 3L      3556000
Rice 5kg            3328000
Body Lotion         2925000
Shampoo             2354000
Sugar 2kg           1272000
Toothpaste           924000
Name: Total_Sales, dtype: int64

In [62]:
top_5_products = revenue_by_product.head(5)

top_5_products

Product
Smartphone         72250000
Jacket             15600000
Blender            15120000
Electric Kettle    11020000
Headphones         10920000
Name: Total_Sales, dtype: int64

Units sold by product

In [63]:
units_by_product = (
    df.groupby("Product")["Quantity"]
    .sum()
    .sort_values(ascending=False)
)

units_by_product.head(5)

Product
Cooking Oil 3L     127
Body Lotion        117
Electric Kettle    116
Shampoo            107
Jeans              107
Name: Quantity, dtype: int64

Monthly revenue

In [64]:
monthly_revenue = (
    df.groupby("Year_Month")["Total_Sales"]
    .sum()
)

monthly_revenue

Year_Month
2026-01    31683000
2026-02    20505000
2026-03    27660000
2026-04    23963000
2026-05    26833000
2026-06    21192000
2026-07    15268000
Name: Total_Sales, dtype: int64

Exploratory Data Analysis & Visualization

In [65]:
import pandas as pd
import plotly.express as px

Question 1 — Which branch generates the most revenue?

In [66]:
branch_revenue = (
    df.groupby("Branch")["Total_Sales"]
    .sum()
    .reset_index()
)

branch_revenue

    Branch  Total_Sales
0  Entebbe     55560000
1    Jinja     55816000
2  Kampala     55728000

Now sort it:

In [68]:
branch_revenue = branch_revenue.sort_values(
    "Total_Sales",
    ascending=False
)

branch_revenue

    Branch  Total_Sales
1    Jinja     55816000
2  Kampala     55728000
0  Entebbe     55560000

Create the chart

In [69]:
fig = px.bar(
    branch_revenue,
    x="Branch",
    y="Total_Sales",
    title="Revenue by Branch",
    labels={"Total_Sales": "Revenue (UGX)"}
)

fig.show()

Question 2 — Which categories generate the most revenue?

In [71]:
category_revenue = (
    df.groupby("Category")["Total_Sales"]
    .sum()
    .reset_index()
    .sort_values("Total_Sales", ascending=False)
)

category_revenue

         Category  Total_Sales
1     Electronics     90990000
3  Home & Kitchen     32965000
0        Clothing     28790000
2       Groceries      8156000
4   Personal Care      6203000

In [72]:
fig = px.bar(
    category_revenue,
    x="Category",
    y="Total_Sales",
    title="Revenue by Product Category",
    labels={"Total_Sales": "Revenue (UGX)"}
)

fig.show()

Question 3 — Which products generate the most revenue?

In [74]:
product_revenue = (
    df.groupby("Product")["Total_Sales"]
    .sum()
    .reset_index()
    .sort_values("Total_Sales", ascending=False)
)

product_revenue.head()

            Product  Total_Sales
11       Smartphone     72250000
6            Jacket     15600000
0           Blender     15120000
3   Electric Kettle     11020000
5        Headphones     10920000

In [75]:
top_5_products = product_revenue.head(5)

top_5_products

            Product  Total_Sales
11       Smartphone     72250000
6            Jacket     15600000
0           Blender     15120000
3   Electric Kettle     11020000
5        Headphones     10920000

In [76]:
fig = px.bar(
    top_5_products,
    x="Product",
    y="Total_Sales",
    title="Top 5 Products by Revenue",
    labels={"Total_Sales": "Revenue (UGX)"}
)

fig.show()

Revenue and popularity are different  
 
This is an important business concept.  

The product generating the most money may not be the product selling the most units.

Let's examine quantity separately.

In [77]:
product_quantity = (
    df.groupby("Product")["Quantity"]
    .sum()
    .reset_index()
    .sort_values("Quantity", ascending=False)
)

product_quantity.head()

            Product  Quantity
2    Cooking Oil 3L       127
1       Body Lotion       117
3   Electric Kettle       116
10          Shampoo       107
7             Jeans       107

In [78]:
top_5_quantity = product_quantity.head(5)

In [79]:
fig = px.bar(
    top_5_quantity,
    x="Product",
    y="Quantity",
    title="Top 5 Products by Units Sold",
    labels={"Quantity": "Units Sold"}
)

fig.show()

Question 4 — How is revenue changing over time?

In [80]:
monthly_revenue = (
    df.groupby("Year_Month")["Total_Sales"]
    .sum()
    .reset_index()
)

monthly_revenue

  Year_Month  Total_Sales
0    2026-01     31683000
1    2026-02     20505000
2    2026-03     27660000
3    2026-04     23963000
4    2026-05     26833000
5    2026-06     21192000
6    2026-07     15268000

In [81]:
fig = px.line(
    monthly_revenue,
    x="Year_Month",
    y="Total_Sales",
    markers=True,
    title="Monthly Revenue Trend",
    labels={
        "Year_Month": "Month",
        "Total_Sales": "Revenue (UGX)"
    }
)

fig.show()

Question 5 — How do customers pay?

In [82]:
payment_counts = (
    df["Payment_Method"]
    .value_counts()
    .reset_index()
)

payment_counts.columns = [
    "Payment_Method",
    "Transactions"
]

payment_counts

  Payment_Method  Transactions
0           Card           174
1   Mobile Money           169
2           Cash           157

In [83]:
fig = px.bar(
    payment_counts,
    x="Payment_Method",
    y="Transactions",
    title="Transactions by Payment Method"
)

fig.show()

In [84]:
fig = px.pie(
    payment_counts,
    names="Payment_Method",
    values="Transactions",
    title="Payment Method Distribution"
)

fig.show()

Question 6 — New vs Regular customers

In [85]:
customer_counts = (
    df["Customer_Type"]
    .value_counts()
    .reset_index()
)

customer_counts.columns = [
    "Customer_Type",
    "Transactions"
]

customer_counts

  Customer_Type  Transactions
0       Regular           262
1           New           238

In [86]:
fig = px.bar(
    customer_counts,
    x="Customer_Type",
    y="Transactions",
    title="Transactions by Customer Type"
)

fig.show()

Which customer type generates more revenue?

In [87]:
customer_revenue = (
    df.groupby("Customer_Type")["Total_Sales"]
    .sum()
    .reset_index()
)

customer_revenue

  Customer_Type  Total_Sales
0           New     85749000
1       Regular     81355000

In [88]:
fig = px.bar(
    customer_revenue,
    x="Customer_Type",
    y="Total_Sales",
    title="Revenue by Customer Type",
    labels={"Total_Sales": "Revenue (UGX)"}
)

fig.show()

Question 7 — Which weekdays generate the most revenue?

In [90]:
weekday_revenue = (
    df.groupby("Day_Name")["Total_Sales"]
    .sum()
    .reset_index()
)

weekday_revenue

    Day_Name  Total_Sales
0     Friday     21841000
1     Monday     20724000
2   Saturday     24503000
3     Sunday     19986000
4   Thursday     28642000
5    Tuesday     21937000
6  Wednesday     29471000

In [91]:
day_order = [
    "Monday",
    "Tuesday",
    "Wednesday",
    "Thursday",
    "Friday",
    "Saturday",
    "Sunday"
]

In [92]:
fig = px.bar(
    weekday_revenue,
    x="Day_Name",
    y="Total_Sales",
    title="Revenue by Day of Week",
    labels={
        "Day_Name": "Day",
        "Total_Sales": "Revenue (UGX)"
    },
    category_orders={
        "Day_Name": day_order
    }
)

fig.show()

Question 8 — How do branches perform by category?

Does every branch earn its revenue from the same product categories?

In [94]:
branch_category_revenue = (
    df.groupby(["Branch", "Category"])["Total_Sales"]
    .sum()
    .reset_index()
)

branch_category_revenue

     Branch        Category  Total_Sales
0   Entebbe        Clothing     13125000
1   Entebbe     Electronics     31170000
2   Entebbe       Groceries      2820000
3   Entebbe  Home & Kitchen      6640000
4   Entebbe   Personal Care      1805000
5     Jinja        Clothing      8030000
6     Jinja     Electronics     26565000
7     Jinja       Groceries      3084000
8     Jinja  Home & Kitchen     15850000
9     Jinja   Personal Care      2287000
10  Kampala        Clothing      7635000
11  Kampala     Electronics     33255000
12  Kampala       Groceries      2252000
13  Kampala  Home & Kitchen     10475000
14  Kampala   Personal Care      2111000

In [95]:
fig = px.bar(
    branch_category_revenue,
    x="Branch",
    y="Total_Sales",
    color="Category",
    title="Revenue by Branch and Category",
    labels={"Total_Sales": "Revenue (UGX)"}
)

fig.show()

Average transaction value by branch  

Which branch has customers spending more per transaction?

In [96]:
branch_average = (
    df.groupby("Branch")["Total_Sales"]
    .mean()
    .reset_index()
    .sort_values("Total_Sales", ascending=False)
)

branch_average

    Branch    Total_Sales
0  Entebbe  342962.962963
2  Kampala  341889.570552
1    Jinja  318948.571429

In [97]:
fig = px.bar(
    branch_average,
    x="Branch",
    y="Total_Sales",
    title="Average Transaction Value by Branch",
    labels={"Total_Sales": "Average Transaction Value (UGX)"}
)

fig.show()

Compare transactions by branch

In [98]:
branch_transactions = (
    df.groupby("Branch")["Transaction_ID"]
    .nunique()
    .reset_index()
)

branch_transactions.columns = [
    "Branch",
    "Transactions"
]

branch_transactions

    Branch  Transactions
0  Entebbe           162
1    Jinja           175
2  Kampala           163

In [99]:
fig = px.bar(
    branch_transactions,
    x="Branch",
    y="Transactions",
    title="Number of Transactions by Branch"
)

fig.show()

Create our KPI summary

In [100]:
total_revenue = df["Total_Sales"].sum()

total_transactions = df["Transaction_ID"].nunique()

total_units = df["Quantity"].sum()

average_transaction_value = (
    total_revenue / total_transactions
)

In [101]:
print(f"Total Revenue: UGX {total_revenue:,.0f}")
print(f"Total Transactions: {total_transactions:,}")
print(f"Total Units Sold: {total_units:,}")
print(
    f"Average Transaction Value: "
    f"UGX {average_transaction_value:,.0f}"
)

Total Revenue: UGX 167,104,000
Total Transactions: 500
Total Units Sold: 1,513
Average Transaction Value: UGX 334,208

useful EDA summary table

In [102]:
product_summary = (
    df.groupby(["Product", "Category"])
    .agg(
        Units_Sold=("Quantity", "sum"),
        Revenue=("Total_Sales", "sum"),
        Transactions=("Transaction_ID", "nunique")
    )
    .reset_index()
)

product_summary.head()

           Product        Category  Units_Sold   Revenue  Transactions
0          Blender  Home & Kitchen          84  15120000            29
1      Body Lotion   Personal Care         117   2925000            33
2   Cooking Oil 3L       Groceries         127   3556000            42
3  Electric Kettle  Home & Kitchen         116  11020000            38
4       Frying Pan  Home & Kitchen         105   6825000            36

In [103]:
product_summary = product_summary.sort_values(
    "Revenue",
    ascending=False
)

product_summary

            Product        Category  Units_Sold   Revenue  Transactions
11       Smartphone     Electronics          85  72250000            27
6            Jacket        Clothing         104  15600000            35
0           Blender  Home & Kitchen          84  15120000            29
3   Electric Kettle  Home & Kitchen         116  11020000            38
5        Headphones     Electronics          91  10920000            34
7             Jeans        Clothing         107   9095000            36
8        Laptop Bag     Electronics          92   7820000            28
4        Frying Pan  Home & Kitchen         105   6825000            36
13          T-Shirt        Clothing          91   4095000            28
2    Cooking Oil 3L       Groceries         127   3556000            42
9          Rice 5kg       Groceries         104   3328000            35
1       Body Lotion   Personal Care         117   2925000            33
10          Shampoo   Personal Care         107   2354000            36
12        Sugar 2kg       Groceries         106   1272000            35
14       Toothpaste   Personal Care          77    924000            28

Create a bar chart showing total revenue by payment method.

In [106]:
total_revenue_by_payment_method = (
    df.groupby('Payment_Method')['Total_Sales']
    .sum()
    .reset_index()
)

In [108]:
fig = px.bar(
    total_revenue_by_payment_method,
    x = 'Payment_Method',
    y = 'Total_Sales',
    title = "Total Revenue By Payment Method"
)
fig.show()

In [109]:
total_revenue_by_payment_method = (
    df.groupby("Payment_Method")["Total_Sales"]
    .sum()
    .reset_index()
    .sort_values("Total_Sales", ascending=False)
)

fig = px.bar(
    total_revenue_by_payment_method,
    x="Payment_Method",
    y="Total_Sales",
    title="Total Revenue by Payment Method",
    labels={
        "Payment_Method": "Payment Method",
        "Total_Sales": "Revenue (UGX)"
    }
)

fig.show()